spring:
  application:
    name: happygear
  datasource:
    url: jdbc:mysql://localhost:3306/happygear
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

server:
  port: 8080
  servlet:
    context-path: /happygear